In [70]:
import pandas as pd
import numpy as np

In [71]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [72]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [73]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [74]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [75]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Handling Dates

In [76]:
date['date'] = pd.to_datetime(date['date'])

In [77]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [78]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [79]:
date['date_month'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [80]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [81]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [82]:
date['date_day_Of_year'] = date['date'].dt.day_of_year
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_Of_year
0,2019-12-10,5628,25,3,2019,12,December,10,344
1,2018-08-15,3646,14,157,2018,8,August,15,227
2,2018-10-23,1859,25,1,2018,10,October,23,296
3,2019-08-17,7292,25,1,2019,8,August,17,229
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [83]:
date['date_day_Of_week'] = date['date'].dt.day_of_week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_Of_year,date_day_Of_week
0,2019-12-10,5628,25,3,2019,12,December,10,344,1
1,2018-08-15,3646,14,157,2018,8,August,15,227,2
2,2018-10-23,1859,25,1,2018,10,October,23,296,1
3,2019-08-17,7292,25,1,2019,8,August,17,229,5
4,2019-01-06,4344,25,3,2019,1,January,6,6,6

In [84]:
date['date_day_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_Of_year,date_day_Of_week,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,10,344,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,227,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,296,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,229,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,6,Sunday

## Handling Time

In [85]:
time['date'] = pd.to_datetime(time['date'])

In [86]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [88]:
time['hour'] = time['date'].dt.hour

In [90]:
time.head()

                 date                                                msg  hour
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37     0
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826    23
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576     0
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...     0
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше    23

In [91]:
time['minute'] = time['date'].dt.minute

In [92]:
time['second'] = time['date'].dt.second

In [93]:
time['time_only'] = time['date'].dt.time

In [94]:
time.head()

,date,msg,hour,minute,second,time_only
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [95]:
time['date'].dt.strftime('%H:%M')

0      00:50
1      23:40
2      00:21
3      00:31
4      23:11
       ...
995    00:50
996    23:14
997    23:37
998    23:34
999    23:25
Name: date, Length: 1000, dtype: object

In [96]:
time['date'].dt.strftime('%p')

0      AM
1      PM
2      AM
3      AM
4      PM
       ..
995    AM
996    PM
997    PM
998    PM
999    PM
Name: date, Length: 1000, dtype: object

In [97]:
def session(x):
    if x < 12:
        return 'Morning'
    elif x < 17:
        return 'Afternoon'
    elif x < 21:
        return 'Evening'
    else:
        return 'Night'

time['session'] = time['hour'].apply(session)

In [98]:
import datetime

today = datetime.datetime.today()

today - time['date']

0     4549 days 09:55:15.145272
1     4413 days 11:05:15.145272
2     4899 days 10:24:15.145272
3     4201 days 10:14:15.145272
4     4598 days 11:34:15.145272
                 ...
995   5188 days 09:55:15.145272
996   4509 days 11:31:15.145272
997   4974 days 11:08:15.145272
998   5090 days 11:11:15.145272
999   4362 days 11:20:15.145272
Name: date, Length: 1000, dtype: timedelta64[ns]

In [99]:
(today - time['date']).dt.days

0      4549
1      4413
2      4899
3      4201
4      4598
       ...
995    5188
996    4509
997    4974
998    5090
999    4362
Name: date, Length: 1000, dtype: int64